version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: pulse_mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: pulse_app
    command: ["--replSet", "rs0"]
    ports:
      - "27017:27017"
    volumes:
      - pulse_mongo_data:/data/db
      - ./init-db/init.js:/docker-entrypoint-initdb.d/init.js:ro
    networks:
      - pulse-network

  backend:
    build: ./Backend
    container_name: pulse_backend
    ports:
      - "3001:3001"
    env_file:
      - ./Backend/.env
    restart: always
    depends_on:
      - mongodb
    networks:
      - pulse-network

  frontend:
    build: ./Frontend
    container_name: pulse_frontend
    ports:
      - "5173:5173"
    restart: always
    depends_on:
      - backend
    networks:
      - pulse-network

volumes:
  pulse_mongo_data:

networks:
  pulse-network:
    driver: bridge